# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "_devops/puppet/manifests"
    puppet.manifest_file = 'default.pp'
    puppet.module_path = '_devops/puppet/modules'
    puppet.options = ['--verbose']
  end

  config.vm.synced_folder ".", "/vagrant"

  config.vm.synced_folder ".", "/var/www/@@PROJECT@@"
end
