# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "default" do |default|
    default.vm.box = "ubuntu/trusty64"

    default.vm.box_check_update = false

    default.vm.network "forwarded_port", guest: 80, host: 8080

    default.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "_devops/puppet/manifests"
      puppet.manifest_file = 'default.pp'
      puppet.module_path = '_devops/puppet/modules'
      puppet.options = ['--verbose']
    end

    default.vm.synced_folder ".", "/vagrant"

    default.vm.synced_folder ".", "/var/www/@@PROJECT@@"
  end
end
